package: svgcrop
version: '0.2.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/svgcrop

pages:
    mediapool/svgcrop:
        title: svgcrop
        hidden: true
        pjax: true
        perm: svgcrop[]

requires:
    redaxo: '^5.18.1'
    php:
        version: '>=8.1, <9'

default_config:
    show_edit_in_list: 1
    svg_edit_url: '/assets/addons/svgcrop/vendor/svgedit/index.html'
